TYPE=VIEW
query=select `C`.`categoria` AS `categoria`,`N`.`subcategoria` AS `subcategoria`,`P`.`provincia` AS `provincia`,`M`.`localidad` AS `localidad`,`Co`.`departamento` AS `departamento`,`N`.`nombre` AS `nombre`,`N`.`direccion` AS `direccion`,`N`.`piso` AS `piso`,`N`.`cp` AS `cp`,`N`.`cod_area` AS `cod_area`,`N`.`telefono` AS `telefono`,`N`.`mail` AS `mail`,`N`.`web` AS `web`,`T`.`tipo_gestion` AS `tipo_gestion`,`N`.`pantallas` AS `pantallas`,`N`.`butacas` AS `butacas`,`N`.`ano_actualizacion` AS `ano_actualizacion`,`N`.`ano_inicio` AS `ano_inicio`,`N`.`capacidad` AS `capacidad`,`Den`.`denominacion_especifica` AS `denominacion_especifica`,`N`.`jurisdiccion_declaratoria` AS `jurisdiccion_declaratoria`,`N`.`fecha_inauguracion` AS `fecha_inauguracion`,`D`.`decreto_o_ley` AS `decreto_o_ley`,`N`.`numero` AS `numero`,`J`.`jurisdiccion` AS `jurisdiccion`,`N`.`ano_inauguracion` AS `ano_inauguracion` from ((((((((`MapaCultural`.`actividades_norm` `N` left join `MapaCultural`.`categorias` `C` on((`N`.`id_categoria` = `C`.`id_categoria`))) left join `MapaCultural`.`provincias` `P` on((`N`.`id_provincia` = `P`.`id_provincia`))) left join `MapaCultural`.`localidades` `M` on((`N`.`id_localidad` = `M`.`id_localidad`))) left join `MapaCultural`.`departamentos` `Co` on((`N`.`id_departamento` = `Co`.`id_departamento`))) left join `MapaCultural`.`tipo_gestiones` `T` on((`N`.`id_tipo_gestion` = `T`.`id_tipo_gestion`))) left join `MapaCultural`.`decreto_o_leyes` `D` on((`N`.`id_decreto_o_ley` = `D`.`id_decreto_o_ley`))) left join `MapaCultural`.`jurisdicciones` `J` on((`N`.`id_jurisdiccion` = `J`.`id_jurisdiccion`))) left join `MapaCultural`.`denominacion_especificas` `Den` on((`N`.`id_denominacion_especifica` = `Den`.`id_denominacion_especifica`)))
md5=620743a5d978f350e52bb5552ea2b49a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2022-03-11 17:48:41
create-version=1
source=SELECT  C.categoria, N.subcategoria, P.provincia, M.localidad, Co.departamento, N.nombre, N.direccion, N.piso, N.cp, N.cod_area, N.telefono, N.mail, N.web, T.tipo_gestion, N.pantallas, N.butacas, N.ano_actualizacion, N.ano_inicio, N.capacidad, Den.denominacion_especifica, N.jurisdiccion_declaratoria, N.fecha_inauguracion,D.decreto_o_ley, N.numero, J.jurisdiccion, N.ano_inauguracion\nFROM actividades_norm as N \nLEFT JOIN categorias as C on N.id_categoria = C.id_categoria\nLEFT JOIN provincias as P on N.id_provincia = P.id_provincia  \nLEFT JOIN localidades as M on N.id_localidad = M.id_localidad\nLEFT JOIN departamentos as Co on N.id_departamento = Co.id_departamento\nLEFT JOIN tipo_gestiones as T on N.id_tipo_gestion = T.id_tipo_gestion\nLEFT JOIN decreto_o_leyes as D on N.id_decreto_o_ley = D.id_decreto_o_ley \nLEFT JOIN jurisdicciones as J on N.id_jurisdiccion = J.id_jurisdiccion\nLEFT JOIN denominacion_especificas as Den on N.id_denominacion_especifica = Den.id_denominacion_especifica
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `C`.`categoria` AS `categoria`,`N`.`subcategoria` AS `subcategoria`,`P`.`provincia` AS `provincia`,`M`.`localidad` AS `localidad`,`Co`.`departamento` AS `departamento`,`N`.`nombre` AS `nombre`,`N`.`direccion` AS `direccion`,`N`.`piso` AS `piso`,`N`.`cp` AS `cp`,`N`.`cod_area` AS `cod_area`,`N`.`telefono` AS `telefono`,`N`.`mail` AS `mail`,`N`.`web` AS `web`,`T`.`tipo_gestion` AS `tipo_gestion`,`N`.`pantallas` AS `pantallas`,`N`.`butacas` AS `butacas`,`N`.`ano_actualizacion` AS `ano_actualizacion`,`N`.`ano_inicio` AS `ano_inicio`,`N`.`capacidad` AS `capacidad`,`Den`.`denominacion_especifica` AS `denominacion_especifica`,`N`.`jurisdiccion_declaratoria` AS `jurisdiccion_declaratoria`,`N`.`fecha_inauguracion` AS `fecha_inauguracion`,`D`.`decreto_o_ley` AS `decreto_o_ley`,`N`.`numero` AS `numero`,`J`.`jurisdiccion` AS `jurisdiccion`,`N`.`ano_inauguracion` AS `ano_inauguracion` from ((((((((`MapaCultural`.`actividades_norm` `N` left join `MapaCultural`.`categorias` `C` on((`N`.`id_categoria` = `C`.`id_categoria`))) left join `MapaCultural`.`provincias` `P` on((`N`.`id_provincia` = `P`.`id_provincia`))) left join `MapaCultural`.`localidades` `M` on((`N`.`id_localidad` = `M`.`id_localidad`))) left join `MapaCultural`.`departamentos` `Co` on((`N`.`id_departamento` = `Co`.`id_departamento`))) left join `MapaCultural`.`tipo_gestiones` `T` on((`N`.`id_tipo_gestion` = `T`.`id_tipo_gestion`))) left join `MapaCultural`.`decreto_o_leyes` `D` on((`N`.`id_decreto_o_ley` = `D`.`id_decreto_o_ley`))) left join `MapaCultural`.`jurisdicciones` `J` on((`N`.`id_jurisdiccion` = `J`.`id_jurisdiccion`))) left join `MapaCultural`.`denominacion_especificas` `Den` on((`N`.`id_denominacion_especifica` = `Den`.`id_denominacion_especifica`)))
